# Tomcat配置
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
# Http配置
spring:
  # SpringBoot映射的静态资源目录，可直接从浏览器上获取
  resources:
    static-locations: classpath:/META-INF/resources,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/